image:https://badges.gitter.im/spring-projects/spring-session.svg[link="https://gitter.im/spring-projects/spring-session?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

image:https://travis-ci.org/spring-projects/spring-session.svg?branch=master["Build Status", link="https://travis-ci.org/spring-projects/spring-session-data-geode"]

= Spring Session for Apache Geode & Pivotal GemFire

_Spring Session_ aims to provide a common infrastructure for managing Sessions.

_Spring Session for Apache Geode_ positions either https://pivotal.io/pivotal-gemfire[Pivotal GemFire]
or http://geode.apache.org/[Apache Geode] as a Session Repository provider.

This provides many benefits including:

* Accessing a Session from any environment (i.e. web, messaging infrastructure, etc)
* In a web environment
** Support for clustering in a vendor/technology neutral way
** Pluggable strategy for determining the Session ID
** Easily keep the HttpSession alive when a WebSocket is active

== Code of Conduct

This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct].
By participating, you  are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Documentation

The documentation for current Spring Session for Apache Geode and Pivotal GemFire can be found
https://docs.spring.io/autorepo/docs/spring-session-data-geode-build/2.0.5.RELEASE/reference/html5/[here].

= Spring Session Project Site

You can find the documentation, issue management, support, samples, and guides for using _Spring Session_
at http://projects.spring.io/spring-session/

= License

_Spring Session_ is Open Source Software released under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
