= Spring Session - HttpSession with Apache Geode Client/Server using Spring Boot
John Blum
:toc:

This guide describes how to build a _Spring Boot_ application configured with _Spring Session_ to transparently leverage
Apache Geode to manage a web application's `javax.servlet.http.HttpSession`.

In this sample, Apache Geode's client/server topology is employed using a pair of _Spring Boot_ applications, one to
configure and run a Apache Geode Server and another to configure and run the cache client, Spring MVC-based web application
making use of the `HttpSession`.

NOTE: The completed guide can be found in the
<<spring-session-sample-boot-geode,Spring Boot Sample Web Application with an Apache Geode managed HttpSession>>.

== Updating Dependencies

Before using _Spring Session_, you must ensure that the required dependencies are included.
If you are using _Maven_, include the following `dependencies` in your `pom.xml`:

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... -->

	<dependency>
		<groupId>org.springframework.session</groupId>
		<artifactId>spring-session-data-geode</artifactId>
		<version>${spring-session-data-geode-version}</version>
		<type>pom</type>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
</dependencies>
----

ifeval::["{version-snapshot}" == "true"]
Since we are using a SNAPSHOT version, we need to add the _Spring_ Snapshot Maven Repository.
If you are using _Maven_, include the following `repository` declaration in your `pom.xml`:

.pom.xml
[source,xml]
----
<repositories>
	<!-- ... -->

	<repository>
		<id>spring-snapshot</id>
		<url>https://repo.spring.io/libs-snapshot</url>
	</repository>
</repositories>
----
endif::[]

ifeval::["{version-milestone}" == "true"]
Since we are using a Milestone version, we need to add the _Spring_ Milestone Maven Repository.
If you are using _Maven_, include the following `repository` declaration in your `pom.xml`:

.pom.xml
[source,xml]
----
<repositories>
	<!-- ... -->

	<repository>
		<id>spring-milestone</id>
		<url>https://repo.spring.io/libs-milestone</url>
	</repository>
</repositories>
----
endif::[]

// tag::config[]
[[httpsession-spring-java-configuration-gemfire-boot]]
== Spring Boot Configuration

After adding the required dependencies and repository declarations, we can create the _Spring_ configuration
for both our Apache Geode client and server using _Spring Boot_.  The _Spring_ configuration is responsible for
creating a `Servlet Filter` that replaces the `HttpSession` with an implementation backed by _Spring Session_
and Apace Geode.

=== Spring Boot, Apache Geode Cache Server

We start with a _Spring Boot_ application to configure and bootstrap the Apache Geode Server process...

[source,java]
----
include::{samples-dir}boot/gemfire/src/main/java/sample/server/GemFireServer.java[tags=class]
----

<1> First, we annotate the Apache Geode Server configuration class with `@SpringBootApplication` to indicate that
this will be a _Spring Boot_ application in order to leverage all of _Spring Boot's_ features (e.g. _auto-configuration_).
<2> Next, we use the **new** _Spring Data Geode_ configuration annotation `@CacheServerApplication` to simplify
the creation of a peer cache instance along with a `CacheServer` for cache clients to connect.
<3> (Optional) Then, the `@EnableGemFireHttpSession` annotation is declared to create the necessary server-side `Region`
(by default, "_ClusteredSpringSessions_") used to store the `HttpSessions` state.  This step is optional since the
Session `Region` could be created manually, perhaps using external means.  Using `@EnableGemFireHttpSession` is convenient.
<4> Additionally, we enable the Apache Geode Manager embedded service, which allows JMX clients (e.g. Apache Geode's
_Gfsh_ shell tool) to connect to the server and inspect the configuration.
<5> Finally, we adjust the port that the `CacheServer` will use to listen for cache clients by declaring
a `CacheServerConfigurer` bean to modify the SDG `CacheServerFactoryBean` using property placeholders.

The sample also makes use of _Spring's_ `PropertySourcesPlaceholderConfigurer` in order to externalize
the sample application's configuration using a properties file or with JVM System properties, which ever.

=== Spring Boot, Apache Geode Cache Client Web application

Now, we create a _Spring Boot_ Web application to expose our Web service with _Spring_ MVC, running as an Apache Geode
cache client connected to our _Spring Boot_, Apache Geode Server.  The Web application will use _Spring Session_
backed by Apache Geode to manage Session state in a clustered (distributed), replicated fashion.

[source,java]
----
include::{samples-dir}boot/gemfire/src/main/java/sample/client/Application.java[tags=class]
----

<1> Again, we declare our Web application to be a _Spring Boot_ application by annotating our application class
with the `@SpringBootApplication` annotation.
<2> `@Controller` is a _Spring_ Web MVC annotation enabling our MVC handler mapping methods (i.e. methods annotated
with `@RequestMapping`) to process HTTP requests (e.g. <6>)
<3> We also declare our Web application to be a Apache Geode cache client by annotating our application class with
`@ClientCacheApplication`.  Additionally, we adjust a few basic, "DEFAULT" `Pool` settings.
<4> Next, we declare that the Web application will use _Spring Session_ backed by Apache Geode by annotating the
`ClientCacheConfiguration` class with `@EnableGemFireHttpSession`.  This will create the necessary client-side `Region`
(by default, "ClusteredSpringSessions`, which is a `PROXY` `Region`) corresponding to the same server-side `Region`
by name. All Session state will be sent from the cache client Web application to the server through `Region`
data access operations.  The client-side `Region` will use the "DEFAULT" `Pool`.
<5> Then, we adjust the port used by the cache client `Pool` to connect to the `CacheServer`
using a SDG `ClientCacheConfigurer`.
<6> We adjust the _Spring_ Web MVC configuration to set the home page, and...
<7> Finally, we declare the `/sessions` HTTP request handler method to set a HTTP Session attribute and increment
a count for the number of HTTP requests.

There are many other useful utility methods, so please refer to the actual source code for full details.

TIP: In typical Apache Geode production deployments, where the cluster includes potentially hundreds or thousands
of Apache Geode servers (data nodes), it is more common for clients to connect to 1 or more Apache Geode Locators running
in the cluster.  A Locator passes meta-data to clients about the servers available in the cluster, the server load
and which servers have the client's data of interest, which is particularly important for direct, single-hop data access
and latency-sensitive operations.  See more details about the
https://geode.apache.org/docs/guide/12/topologies_and_comm/cs_configuration/standard_client_server_deployment.html[Client/Server Deployment]
in the Apache Geode User Guide.

NOTE: For more information on configuring _Spring Data Geode, refer to the
https://docs.spring.io/spring-data-gemfire/docs/current/reference/html/[Reference Guide].

`@EnableGemFireHttpSession` enables a developer to configure certain aspects of both _Spring Session_ and Apache Geode
out-of-the-box using the following attributes:

* `clientRegionShortcut` - specifies Apache Geode https://geode.apache.org/docs/guide/12/developing/region_options/region_types.html[data management policy]
on the client with a Apache Geode https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/client/ClientRegionShortcut.html[ClientRegionShortcut]
(default is `PROXY`).  This attribute is only used when configuring client `Region`.
* `indexableSessionAttributes` - Identifies the Session attributes by name that should be indexed for querying operations.
Only Session attributes identified by name will be indexed.
* `maxInactiveIntervalInSeconds` - controls _HttpSession_ idle-timeout expiration (defaults to **30 minutes**).
* `poolName` - name of the dedicated Apache Geode `Pool` used to connect a client to the cluster of servers.  The attribute
is only used when the application is a cache client.  Defaults to `gemfirePool`.
* `regionName` - specifies the name of the Apache Geode `Region` used to store and manage `HttpSession` state
(default is "*ClusteredSpringSessions*").
* `serverRegionShortcut` - specifies Apache Geode https://geode.apache.org/docs/guide/12/developing/region_options/region_types.html[data management policy]
on the server using a Apache Geode https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/RegionShortcut.html[RegionShortcut]
(default is `PARTITION`).  This attribute is only used when configuring server `Regions`, or when a P2P topology is employed.

NOTE: It is important to remember that the Apache Geode client `Region` name must match a server `Region`
by the same name if the client `Region` is a `PROXY` or `CACHING_PROXY`.  Client and server `Region` names
are not required to match if the client `Region` used to store Sessions is `LOCAL`.  However, keep in mind
that Session state will not be propagated to the server and you lose all the benefits of using Apache Geode
to store and manage distributed, replicated Session state information on the servers in a cluster.

[[spring-session-sample-boot-geode]]
== Spring Boot Sample Web Application with an Apache Geode managed HttpSession

=== Running the Boot Sample Application

You can run the sample by obtaining the {download-url}[source code] and invoking the following commands.

First, you must run the server:

----
$ ./gradlew :spring-session-sample-boot-gemfire:run
----

Then, in a separate terminal, run the client:

----
$ ./gradlew :spring-session-sample-boot-gemfire:bootRun
----

You should now be able to access the application at http://localhost:8080/.

In this sample, the Web application is the _Spring Boot_, Apache Geode cache client
and the server is standalone, separate (JVM) process.

=== Exploring the Boot Sample Application

Try using the application. Fill out the form with the following information:

* **Attribute Name:** _username_
* **Attribute Value:** _test_

Now click the **Set Attribute** button. You should now see the attribute name and value displayed in the table
along with an additional attribute (`requestCount`) indicating the number of Session interactions (via HTTP requests).

=== How does it work?

We interact with the standard `javax.servlet.http.HttpSession` in the the Spring Web MVC service endpoint,
shown here for convenience:

.src/main/java/sample/client/Application.java
[source,java]
----
@RequestMapping(method = RequestMethod.POST, path = "/session")
public String session(HttpSession session, ModelMap modelMap,
		@RequestParam(name = "attributeName", required = false) String name,
		@RequestParam(name = "attributeValue", required = false) String value) {

	modelMap.addAttribute("sessionAttributes",
		attributes(setAttribute(updateRequestCount(session), name, value)));

	return INDEX_TEMPLATE_VIEW_NAME;
}
----

Instead of using the embedded HTTP server's `HttpSession`, we are actually persisting the Session state in Apache Geode.
_Spring Session_ creates a cookie named SESSION in your browser that contains the id of your Session.
Go ahead and view the cookies (click for help with https://developer.chrome.com/devtools/docs/resources#cookies[Chrome]
or https://getfirebug.com/wiki/index.php/Cookies_Panel#Cookies_List[Firefox]).

NOTE: The following instructions assume you have a local Apache Geode installation.  For more information on installation,
see https://geode.apache.org/docs/guide/12/prereq_and_install.html[Prerequisites and Installation Instructions].

If you like, you can easily remove the Session using `gfsh`.

For example, on a Linux-based system type the following at the command-line:

	$ gfsh

Then, enter the following commands in _Gfsh_, ensuring to replace `70002719-3c54-4c20-82c3-e7faa6b718f3` with the value
of your SESSION cookie, or the Session id returned by the Apache Geode OQL query (which should match):

....
gfsh>connect --jmx-manager=localhost[1099]

gfsh>query --query='SELECT * FROM /ClusteredSpringSessions.keySet'

Result     : true
startCount : 0
endCount   : 20
Rows       : 1

Result
------------------------------------
70002719-3c54-4c20-82c3-e7faa6b718f3

NEXT_STEP_NAME : END

gfsh>remove --region=/ClusteredSpringSessions --key="70002719-3c54-4c20-82c3-e7faa6b718f3"
....

NOTE: The _Apache Geode User Guide_ contains more detailed instructions on using
https://geode.apache.org/docs/guide/12/tools_modules/gfsh/chapter_overview.html[gfsh].

Now visit the application at `http://localhost:8080/` again and observe the attribute we added is no longer displayed.

Alternatively, you can wait **20 seconds** for the Session to timeout and expire and then refresh the page.
The attribute we added should no longer be displayed in the table.
