:data-store-version: {master-data-store-version}
:data-store-docs: https://geode.apache.org/docs/guide/{data-store-version}
:stylesdir: ../

NOTE: The following instructions assume you have installed a local Apache Geode installation.  For more information
on installation, see {data-store-docs}/prereq_and_install.html[Prerequisites and Installation Instructions].

If you like, you can easily remove the session using `gfsh`.

For example, on a Linux-based system type the following at the command-line:

	$ gfsh

Then, enter the following commands in _Gfsh_, ensuring to replace `70002719-3c54-4c20-82c3-e7faa6b718f3` with the value
from your SESSION cookie, or the session id returned by the Apache Geode OQL query (which should match):

[source,text]
----
gfsh>connect --jmx-manager=localhost[1099]

gfsh>query --query='SELECT * FROM /ClusteredSpringSessions.keySet'

Result     : true
startCount : 0
endCount   : 20
Rows       : 1

Result
------------------------------------
70002719-3c54-4c20-82c3-e7faa6b718f3

NEXT_STEP_NAME : END

gfsh>remove --region=/ClusteredSpringSessions --key="70002719-3c54-4c20-82c3-e7faa6b718f3"
----

NOTE: The Apache Geode User Guide contains more detailed instructions on using
{data-store-docs}/tools_modules/gfsh/chapter_overview.html[gfsh].

Now visit the application at `http://localhost:8080/` again and observe the attribute we added is no longer displayed.

Alternatively, you can wait **20 seconds** for the session to timeout/expire and then refresh the page. The attribute
we added should no longer be displayed in the table. However, keep in mind, by refreshing the page, you will
inadvertently create a new (empty) session.  If you run the query again, you will also see two session ids,
the new and the old, since Apache Geode keeps a "tombstone" of the old session around (for consistency purposes).
